"""add Department

Revision ID: 0438d8218524
Revises: ff284860d118
Create Date: 2024-10-08 14:43:28.686736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0438d8218524'
down_revision = 'ff284860d118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
