"""rename department

Revision ID: 8e23786b43f6
Revises: 8e93e7578499
Create Date: 2024-10-08 14:56:41.077646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e23786b43f6'
down_revision = '8e93e7578499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('departments', 'department')
    # ### end Alembic commands ###
