"""add address

Revision ID: 8e93e7578499
Revises: 0438d8218524
Create Date: 2024-10-08 14:46:45.206927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e93e7578499'
down_revision = '0438d8218524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'address')
    # ### end Alembic commands ###
